name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Kjør workflow når det pushes til main-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend  # Sett konteksten til backend-mappen
          file: ./backend/Dockerfile  # Angi Dockerfile som ligger i backend-mappen
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
